#apiVersion: http.keda.sh/v1alpha1
#kind: HTTPScaledObject
#metadata:
#  name: llama-server-http-scaledobject
#  namespace: llm-server
#spec:
#  hosts:
#    - llm.internal.pharmeasy.in
#  pathPrefixes:
#    - /
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: StatefulSet          # changed from argoproj.io/v1alpha1 Rollout
#    name: llama-server
#    service: llama-server
#    port: 8080
#  replicas:
#    min: 0
#    max: 2
#  scalingMetric:
#    requestRate:
#      granularity: 1s
#      targetValue: 5
#      window: 1m
