#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: llm-server-ingress
#  namespace: keda                  # ingress must be in keda namespace to hit interceptor
#  annotations:
#    kubernetes.io/ingress.class: alb
#    alb.ingress.kubernetes.io/scheme: internal
#    alb.ingress.kubernetes.io/target-type: ip
#spec:
#  rules:
#    - host: llm.internal.pharmeasy.in
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: keda-add-ons-http-interceptor-proxy
#                port:
#                  number: 8080