# -- Shared --
SHARED_NAMESPACE: ai-hub
env: staging   # <-- add this; set to "production" in prod vars
project_name: ai-hub

# litellm
LITELLM_IMAGE: ghcr.io/berriai/litellm:main-latest
LITELLM_PORT: 4000
LITELLM_REPLICAS: 2
LITELLM_CPU_REQUEST: 250m
LITELLM_MEMORY_REQUEST: 512Mi
LITELLM_CPU_LIMIT: "1"
LITELLM_MEMORY_LIMIT: 1Gi
LITELLM_READINESS_INITIAL_DELAY: 10
LITELLM_READINESS_PERIOD: 5
LITELLM_CONFIG: |
    model_list:
      - model_name: qwen-3b
        litellm_params:
          model: openai/qwen-3b
          api_base: http://ollama-server-3b:8080/v1
          api_key: none